version: 2

sources:
  - name: barcelona_temp_source
    database: spa-datajuniorsprogram-sdb-001   # bigquery project
    schema: temp_db                            # bigquery dataset

    #database: temp_db
    #schema: public
    description: "Temperaturas medias mensuales de Barcelona por a침o"

    tables:
      - name: barcelona_monthly_temp
        description: "Tabla con temperaturas medias mensuales hist칩ricas"

        # Asegura 1 fila por a침o
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - any_year

        columns:
          - name: any_year
            description: "A침o de referencia"
            tests:
              - not_null

          - name: temp_gener
            description: "Temperatura media de enero"
            tests:
              - not_null

          - name: temp_febrer
            description: "Temperatura media de febrero"
            tests:
              - not_null

          - name: temp_marc
            description: "Temperatura media de marzo"
            tests:
              - not_null

          - name: temp_abril
            description: "Temperatura media de abril"
            tests:
              - not_null

          - name: temp_maig
            description: "Temperatura media de mayo"
            tests:
              - not_null

          - name: temp_juny
            description: "Temperatura media de junio"
            tests:
              - not_null

          - name: temp_juliol
            description: "Temperatura media de julio"
            tests:
              - not_null

          - name: temp_agost
            description: "Temperatura media de agosto"
            tests:
              - not_null

          - name: temp_setembre
            description: "Temperatura media de septiembre"
            tests:
              - not_null

          - name: temp_octubre
            description: "Temperatura media de octubre"
            tests:
              - not_null

          - name: temp_novembre
            description: "Temperatura media de noviembre"
            tests:
              - not_null

          - name: temp_desembre
            description: "Temperatura media de diciembre"
            tests:
              - not_null
